# 더이상 업그레이드할 수 없는 아이템 정보 출력
# 자식이 없는 아이템

SELECT A.ITEM_ID, A.ITEM_NAME, A.RARITY
FROM ITEM_INFO A
WHERE A.ITEM_ID NOT IN (SELECT B.ITEM_ID FROM ITEM_TREE B JOIN ITEM_TREE C ON B.ITEM_ID = C.PARENT_ITEM_ID)
ORDER BY A.ITEM_ID DESC;