SELECT 
    C.CAR_ID,
    C.CAR_TYPE,
    CAST(C.DAILY_FEE * 30 * (1 - P.DISCOUNT_RATE/100) AS SIGNED) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
  ON C.CAR_TYPE = P.CAR_TYPE
 AND P.DURATION_TYPE = '30일 이상'
WHERE (C.CAR_TYPE = '세단' OR C.CAR_TYPE = 'SUV')
  AND NOT EXISTS (
        SELECT 1
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
        WHERE H.CAR_ID = C.CAR_ID
          AND H.START_DATE <= '2022-11-30'
          AND H.END_DATE >= '2022-11-01'
  )
  AND (C.DAILY_FEE * 30 * (1 - P.DISCOUNT_RATE/100)) >= 500000
  AND (C.DAILY_FEE * 30 * (1 - P.DISCOUNT_RATE/100)) < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;
