# 음식 종류별로 즐겨찾기수가 가장 많은 식당 정보 출력

SELECT A.FOOD_TYPE, A.REST_ID, A.REST_NAME, A.FAVORITES
FROM REST_INFO A
JOIN (SELECT MAX(FAVORITES) AS MF, FOOD_TYPE FROM REST_INFO GROUP BY FOOD_TYPE) B
ON A.FAVORITES = B.MF AND A.FOOD_TYPE = B.FOOD_TYPE
ORDER BY FOOD_TYPE DESC;
