SELECT 
    YEAR(S.SALES_DATE)  AS YEAR,
    MONTH(S.SALES_DATE) AS MONTH,
    A.GENDER,
    COUNT(DISTINCT A.USER_ID) AS USERS
FROM USER_INFO A
JOIN ONLINE_SALE S 
  ON A.USER_ID = S.USER_ID
WHERE A.GENDER IS NOT NULL
GROUP BY YEAR(S.SALES_DATE), MONTH(S.SALES_DATE), A.GENDER
ORDER BY YEAR, MONTH, GENDER;
