WITH RECURSIVE T AS (
  -- 1세대(루트들)
  SELECT
    ID,
    PARENT_ID,
    1 AS GENERATION
  FROM ECOLI_DATA
  WHERE PARENT_ID IS NULL

  UNION ALL

  -- 자식으로 내려가며 세대 + 1
  SELECT
    E.ID,
    E.PARENT_ID,
    T.GENERATION + 1
  FROM ECOLI_DATA E
  JOIN T ON E.PARENT_ID = T.ID
)
SELECT
  COUNT(*) AS COUNT,
  GENERATION
FROM T
WHERE NOT EXISTS (                      -- 자식이 없으면 리프
  SELECT 1
  FROM ECOLI_DATA X
  WHERE X.PARENT_ID = T.ID
)
GROUP BY GENERATION
ORDER BY GENERATION;
