WITH RECURSIVE GEN AS (
    -- 1세대: 부모가 없는 개체
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    -- 자식 세대: 부모 세대 + 1
    SELECT E.ID, E.PARENT_ID, G.GENERATION + 1
    FROM ECOLI_DATA E
    JOIN GEN G ON E.PARENT_ID = G.ID
)
SELECT COUNT(ID) AS COUNT, GENERATION
FROM GEN
WHERE ID NOT IN (
    SELECT PARENT_ID FROM ECOLI_DATA WHERE PARENT_ID IS NOT NULL
)
GROUP BY GENERATION
ORDER BY GENERATION;
