SELECT C.FLAVOR
FROM (
    SELECT A.FLAVOR, SUM(A.TOTAL_ORDER + B.TOTAL_ORDER) AS TOTAL_SALES
    FROM FIRST_HALF A
    JOIN JULY B ON A.FLAVOR = B.FLAVOR
    GROUP BY FLAVOR
    ) AS C
ORDER BY TOTAL_SALES DESC
LIMIT 3;