# 부모의 형질을 모두 보유한 대장균의 아이디, 형질, 부모 대장균의 형질 출력

SELECT B.ID, B.GENOTYPE, A.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA A
LEFT JOIN ECOLI_DATA B ON A.ID = B.PARENT_ID
WHERE B.GENOTYPE & A.GENOTYPE = A.GENOTYPE
ORDER BY ID ASC;