SELECT A.YEAR, A.MAX - B.SIZE_OF_COLONY AS YEAR_DEV, B.ID
FROM (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX FROM ECOLI_DATA GROUP BY YEAR ORDER BY YEAR) AS A
JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, ID, SIZE_OF_COLONY FROM ECOLI_DATA) AS B
ON A.YEAR = B.YEAR
ORDER BY YEAR, YEAR_DEV
