SELECT 
    C.ID, 
    D.FISH_NAME, 
    C.LENGTH
FROM FISH_INFO C
JOIN (
    SELECT 
        B.FISH_TYPE, 
        B.FISH_NAME, 
        MAX(A.LENGTH) AS MAX_LENGTH
    FROM FISH_INFO A
    JOIN FISH_NAME_INFO B 
        ON A.FISH_TYPE = B.FISH_TYPE
    GROUP BY B.FISH_TYPE, B.FISH_NAME
) D
ON C.FISH_TYPE = D.FISH_TYPE       
AND C.LENGTH = D.MAX_LENGTH     
ORDER BY C.ID ASC;
