SELECT A.ID, B.FISH_NAME, A.LENGTH
FROM FISH_INFO AS A
JOIN FISH_NAME_INFO AS B
  ON A.FISH_TYPE = B.FISH_TYPE
JOIN (
    SELECT B.FISH_NAME, MAX(A.LENGTH) AS MAX_LENGTH
    FROM FISH_INFO AS A
    JOIN FISH_NAME_INFO AS B
      ON A.FISH_TYPE = B.FISH_TYPE
    GROUP BY B.FISH_NAME
) AS M
  ON B.FISH_NAME = M.FISH_NAME
 AND A.LENGTH = M.MAX_LENGTH
ORDER BY A.ID;
