SELECT CONCAT_WS('/', '/home/grep/src', B.BOARD_ID, CONCAT(B.FILE_ID, FILE_NAME, FILE_EXT)) AS FILE_PATH
FROM USED_GOODS_BOARD AS A
JOIN USED_GOODS_FILE AS B
ON A.BOARD_ID = B.BOARD_ID
WHERE A.VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY B.FILE_ID DESC
